In [460]:
import torch
import numpy as np
import torch.nn as nn
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Loading dataset 

In [461]:
data = datasets.load_iris()

In [462]:
data.data[0].shape

(4,)

## Getting Labels

In [463]:
train , output = data.data , data.target

In [464]:
xtrain, xtest, ytrain, ytest = train_test_split(train, output, test_size=0.2, random_state=1234)

In [465]:
len(xtrain)

120

In [466]:
sc = StandardScaler()

In [467]:
fx_train = sc.fit_transform(xtrain)

In [468]:
fx_test = sc.transform(xtest)

In [469]:
xtest

array([[6.1, 3. , 4.6, 1.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.3, 2.9, 5.6, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [4.7, 3.2, 1.6, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 3.9, 1.2],
       [4.4, 3.2, 1.3, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [5.9, 3. , 4.2, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [5.7, 2.6, 3.5, 1. ],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3. , 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.7, 4.2, 1.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.7, 4.9, 1.8],
       [5.8, 2.6, 4. , 1.2],
       [7.1, 3. , 5.9, 2.1],
       [4.8, 3.4, 1.6, 0.2]])

## Converting into Tensor

In [470]:
xtrain, xtest, ytrain, ytest = map(lambda x : torch.from_numpy(x.astype(np.float32)) , [fx_train, fx_test, ytrain, ytest])

## Shaping the output

In [471]:
ytrain = ytrain.view(ytrain.shape[0], 1)
ytest = ytest.view(ytest.shape[0], 1)
ytrain.size()

torch.Size([120, 1])

In [472]:
len(xtest) == len(ytest)

True

## Using Sigmoid Fn

In [473]:
class Logistic(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,1)
    
    def forward(self , pred):
        y_pred = torch.sigmoid(self.linear(pred))
        return y_pred
            

In [474]:
model = Logistic()

In [475]:
list(model.parameters())

[Parameter containing:
 tensor([[0.1410, 0.4531, 0.2693, 0.2709]], requires_grad=True),
 Parameter containing:
 tensor([-0.3996], requires_grad=True)]

## Optimizer

In [476]:
opt = torch.optim.Adam(model.parameters() , lr = 0.01)

In [480]:
loss_fn = nn.BCELoss() # Using Binary cross entroy loss

## Training

In [481]:
for i in range(100):
    pred = model(xtrain)
    loss = loss_fn(pred , ytrain)
    loss.backward()
    opt.step()
    opt.zero_grad()

In [482]:
with torch.no_grad():
    final_pred = model(xtest).round()
    acc = final_pred.eq(ytest).sum()/float(ytest.shape[0])
    print(acc.item())

0.7333333492279053
